FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish PorphyStruct.CLI/PorphyStruct.CLI.csproj -c Release -r linux-musl-x64 \
        /p:IncludeNativeLibrariesForSelfExtract=false /p:IncludeAllContentForSelfExtract=false \
        -o /app/publish

FROM mcr.microsoft.com/dotnet/runtime-deps:8.0-alpine AS runtime
WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["./PorphyStruct.CLI"]
