name: Deploy on Vercel

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: wasm-tooling
      run: dotnet workload install wasm-tools-net7
    - name: publish
      run: |
            cd PorphyStruct.Web
            dotnet publish -c Release
    - name: vercel_json
      run: |
            cp vercel.json ./PorphyStruct.Web/bin/Release/net7.0/publish/wwwroot
    - uses: amondnet/vercel-action@v25
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORGID}}
        vercel-project-id: ${{ secrets.PROJECTID}}
        vercel-args: '--prod --confirm'
        working-directory: ./PorphyStruct.Web/bin/Release/net7.0/publish/wwwroot
